spring:
  application:
    name: mood-app
  datasource:
    url: jdbc:postgresql://localhost:5432/mood-app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  security:
    request-matchers:
      permit-all: >
        POST /users,
        GET /posts